{"name": "Авторизаиця с недействительными учетными данными", "status": "passed", "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1727287106906, "stop": 1727287109820}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1727287109820, "stop": 1727287109986}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "passed", "start": 1727287109986, "stop": 1727287109997}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1727287106906, "stop": 1727287109997, "uuid": "3974299a-9eab-43a0-a858-f820ae77bf73", "historyId": "3230c37a4ddf37e226b736e144aaba65", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "Авторизаци"}, {"name": "story", "value": "Авторизации недействительные учетные данные"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-LKNP7PM"}, {"name": "thread", "value": "15132-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}